//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.11.10 at 04:18:42 PM CET 
//


package de.uniluebeck.itm.vs1112.uebung2.aufgabe211.xml;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for SpeiseplanRequest complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SpeiseplanRequest">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;all>
 *         &lt;element name="dayOfYear" type="{http://itm.uniluebeck.de/vs1112/uebung2/aufgabe211/xml}DayOfYear"/>
 *       &lt;/all>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlRootElement // added by hand - Martin Thurau
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SpeiseplanRequest", propOrder = {

})
public class SpeiseplanRequest {

    protected int dayOfYear;

    /**
     * Gets the value of the dayOfYear property.
     * 
     */
    public int getDayOfYear() {
        return dayOfYear;
    }

    /**
     * Sets the value of the dayOfYear property.
     * 
     */
    public void setDayOfYear(int value) {
        this.dayOfYear = value;
    }

}
