//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.12.05 at 10:51:15 AM MEZ 
//

/**
 * This class must not be modified.
 */
@javax.xml.bind.annotation.XmlSchema(
		namespace = "http://itm.uniluebeck.de/vs1112/uebung4/xml") package de.uniluebeck.itm.vs1112.uebung4.xml;
