//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.11.10 at 09:20:32 AM CET 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://itm.uniluebeck.de/vs1112/uebung2/aufgabe211/xml")
package de.uniluebeck.itm.vs1112.uebung2.aufgabe211.xml;
