//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.12.05 at 10:51:15 AM MEZ 
//


package de.uniluebeck.itm.vs1112.uebung4.xml;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This class must not be modified.
 * <p/>
 * This object contains factory methods for each
 * Java content interface and Java element interface
 * generated in the de.uniluebeck.itm.vs1112.uebung4.xml package.
 * <p>An ObjectFactory allows you to programatically
 * construct new instances of the Java representation
 * for XML content. The Java representation of XML
 * content can consist of schema derived interfaces
 * and classes representing the binding of schema
 * type definitions, element declarations and model
 * groups.  Factory methods for each of these are
 * provided in this class.
 */
@XmlRegistry
public class ObjectFactory {


	/**
	 * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package:
	 * de.uniluebeck.itm.vs1112.uebung4.xml
	 */
	public ObjectFactory() {
	}

	/**
	 * Create an instance of {@link PhoneBookEntry }
	 */
	public PhoneBookEntry createPhoneBookEntry() {
		return new PhoneBookEntry();
	}

	/**
	 * Create an instance of {@link PhoneBookEntryWithUri }
	 */
	public PhoneBookEntryWithUri createPhoneBookEntryWithUri() {
		return new PhoneBookEntryWithUri();
	}

	/**
	 * Create an instance of {@link PhoneBookEntryList }
	 */
	public PhoneBookEntryList createPhoneBookEntryList() {
		return new PhoneBookEntryList();
	}

}
