//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.12.05 at 10:51:15 AM MEZ 
//


package de.uniluebeck.itm.vs1112.uebung4.xml;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import java.util.ArrayList;
import java.util.List;


/**
 * This class must not be modified.
 * <p/>
 * <p>Java class for anonymous complex type.
 * <p/>
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p/>
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="phoneBookEntryWithUri" type="{http://itm.uniluebeck.de/vs1112/uebung4/xml}PhoneBookEntryWithUri"
 * maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
		"phoneBookEntryWithUri"
})
@XmlRootElement(name = "phoneBookEntryList")
public class PhoneBookEntryList {

	protected List<PhoneBookEntryWithUri> phoneBookEntryWithUri;

	/**
	 * Gets the value of the phoneBookEntryWithUri property.
	 * <p/>
	 * <p/>
	 * This accessor method returns a reference to the live list,
	 * not a snapshot. Therefore any modification you make to the
	 * returned list will be present inside the JAXB object.
	 * This is why there is not a <CODE>set</CODE> method for the phoneBookEntryWithUri property.
	 * <p/>
	 * <p/>
	 * For example, to add a new item, do as follows:
	 * <pre>
	 *    getPhoneBookEntryWithUri().add(newItem);
	 * </pre>
	 * <p/>
	 * <p/>
	 * <p/>
	 * Objects of the following type(s) are allowed in the list
	 * {@link PhoneBookEntryWithUri }
	 *
	 * @return a list of entries
	 */
	public List<PhoneBookEntryWithUri> getPhoneBookEntryWithUri() {
		if (phoneBookEntryWithUri == null) {
			phoneBookEntryWithUri = new ArrayList<PhoneBookEntryWithUri>();
		}
		return this.phoneBookEntryWithUri;
	}

	@Override
	public boolean equals(final Object o) {
		if (this == o) {
			return true;
		}
		if (o == null || getClass() != o.getClass()) {
			return false;
		}

		final PhoneBookEntryList list = (PhoneBookEntryList) o;

		return !(phoneBookEntryWithUri != null ? !phoneBookEntryWithUri.equals(list.phoneBookEntryWithUri) :
				list.phoneBookEntryWithUri != null);
	}

	@Override
	public int hashCode() {
		return phoneBookEntryWithUri != null ? phoneBookEntryWithUri.hashCode() : 0;
	}
}
