//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.12.05 at 10:51:15 AM MEZ 
//


package de.uniluebeck.itm.vs1112.uebung4.xml;

import javax.xml.bind.annotation.*;


/**
 * This class must not be modified.
 * <p/>
 * <p>Java class for anonymous complex type.
 * <p/>
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p/>
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="number" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
		"name",
		"number"
})
@XmlRootElement(name = "phoneBookEntry")
public class PhoneBookEntry {

	@XmlElement(required = true)
	protected String name;

	@XmlElement(required = true)
	protected String number;

	/**
	 * Gets the value of the name property.
	 *
	 * @return possible object is
	 *         {@link String }
	 */
	public String getName() {
		return name;
	}

	/**
	 * Sets the value of the name property.
	 *
	 * @param value
	 * 		allowed object is
	 * 		{@link String }
	 */
	public void setName(String value) {
		this.name = value;
	}

	/**
	 * Gets the value of the number property.
	 *
	 * @return possible object is
	 *         {@link String }
	 */
	public String getNumber() {
		return number;
	}

	/**
	 * Sets the value of the number property.
	 *
	 * @param value
	 * 		allowed object is
	 * 		{@link String }
	 */
	public void setNumber(String value) {
		this.number = value;
	}

	@Override
	public boolean equals(final Object o) {
		if (this == o) {
			return true;
		}
		if (o == null || getClass() != o.getClass()) {
			return false;
		}

		final PhoneBookEntry entry = (PhoneBookEntry) o;

		return name.equals(entry.name) && number.equals(entry.number);
	}

	@Override
	public int hashCode() {
		int result = name.hashCode();
		result = 31 * result + number.hashCode();
		return result;
	}
}
