//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.12.05 at 10:51:15 AM MEZ 
//


package de.uniluebeck.itm.vs1112.uebung4.xml;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * This class must not be modified.
 * <p/>
 * <p>Java class for PhoneBookEntryWithUri complex type.
 * <p/>
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p/>
 * <pre>
 * &lt;complexType name="PhoneBookEntryWithUri">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="uri" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element ref="{http://itm.uniluebeck.de/vs1112/uebung4/xml}phoneBookEntry"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PhoneBookEntryWithUri", propOrder = {
		"uri",
		"phoneBookEntry"
})
public class PhoneBookEntryWithUri {

	@XmlElement(required = true)
	protected String uri;

	@XmlElement(namespace = "http://itm.uniluebeck.de/vs1112/uebung4/xml", required = true)
	protected PhoneBookEntry phoneBookEntry;

	/**
	 * Gets the value of the uri property.
	 *
	 * @return possible object is
	 *         {@link String }
	 */
	public String getUri() {
		return uri;
	}

	/**
	 * Sets the value of the uri property.
	 *
	 * @param value
	 * 		allowed object is
	 * 		{@link String }
	 */
	public void setUri(String value) {
		this.uri = value;
	}

	/**
	 * Gets the value of the phoneBookEntry property.
	 *
	 * @return possible object is
	 *         {@link PhoneBookEntry }
	 */
	public PhoneBookEntry getPhoneBookEntry() {
		return phoneBookEntry;
	}

	/**
	 * Sets the value of the phoneBookEntry property.
	 *
	 * @param value
	 * 		allowed object is
	 * 		{@link PhoneBookEntry }
	 */
	public void setPhoneBookEntry(PhoneBookEntry value) {
		this.phoneBookEntry = value;
	}

	@Override
	public boolean equals(final Object o) {
		if (this == o) {
			return true;
		}
		if (o == null || getClass() != o.getClass()) {
			return false;
		}

		final PhoneBookEntryWithUri that = (PhoneBookEntryWithUri) o;

		return phoneBookEntry.equals(that.phoneBookEntry) && uri.equals(that.uri);
	}

	@Override
	public int hashCode() {
		int result = uri.hashCode();
		result = 31 * result + phoneBookEntry.hashCode();
		return result;
	}
}
